### PR TITLE
Updated schema to support parsing delivery medium option form conversation state and updated test accordingly to have all tests passing still

### PR DESCRIPTION
**Pull request by wingc-china**
From my current understandings from the protocol doc of Google Hangouts from http://hangups.readthedocs.org/en/stable/protobuf.html and the code of Hangups, the delivery medium option was not parsed from conversation state yet in current HangupJS release. Because of this, message cannot be delivered to actual end point of chat participant but only the default one. E.g. if a participant uses Google Voice phone number to send SMS to the conversation no message will be delivered to this participant's Google Voice SMS number but only the Hangouts client.

I made some changes in the schema to have the delivery medium option parsed out, which is the first step to ensure delivery success to actually medium. My next change will be to update the "sendchatmessage" to have delivery medium option filled in, following Hangups code change here, https://github.com/tdryer/hangups/commit/45b1165e8c9cf7e1267112c78f046b2070bb6b35

I also updated the test code to ensure all tests passing. Here is the result:
> hangupsjs@1.3.1 test D:\Code\Libs\hangupsjs
> mocha
  . CLIENT_GET_SELF_INFO_RESPONSE parses: 1ms
  . INITIAL_CLIENT_ENTITIES parses: 2ms
  . CLIENT_CONVERSATION_STATE_LIST parses: 5ms
  . Init parseBody takes an html body, evals it and extracts data: 109ms
  . MessageBuilder adds a simple text segment: 0ms
  . MessageBuilder adds a bold text segment: 1ms
  . MessageBuilder adds a italic text segment: 0ms
  . MessageBuilder adds a strikethrough text segment: 1ms
  . MessageBuilder adds an underline text segment: 1ms
  . MessageBuilder adds a link: 0ms
  . MessageBuilder adds a linebreak: 0ms
  . MessagePaser parsePushLines handles noop: 2ms
  . MessagePaser parsePushLines handles {p:{ with clientid: 1ms
  . PushDataParser parses sid/gsid: 4ms
  . PushDataParser handles chopped off len specifications: 0ms
  . PushDataParser handles chopped off data: 1ms
  . PushDataParser allLines is a promise for all the lines read: 1ms
  . CLIENT_SYNC_ALL_NEW_EVENTS_RESPONSE parses: 7ms
  18 passing (225ms)

### CODE REVIEW

**Comment by algesten** [comment]
Cool! I like it! Should we add something to the README about it?

**Comment by wingc-china** [comment]
Makes sense. I will update the README a little bit to reflect this change.

Want to get your opinion on my next change. I planned to add a new parameter delivery_medium to the sendchatmessage and also read the conversation's delivery medium from the conservation state to call to sendchatmessage, just as what the Hangups does. But latter I found the HangupsJS has no mapping conversation APIs but only the low level sendchatmessage. So probably your original design is to provide the low level APIs only and let the users manage conversations themselves. Hope I understand your code right.

Therefore there are two approaches in my mind:
1) if it is okay to clone whatever Hangups does, it is ideal to have conversation managed in HangupsJS and I would follow my original plan. I am afraid this would break your original design and it takes longer to get it done. I am a coffeescript green hand I have to admit.
2) still keep low level APIs only but make the sendchatmessage a little advanced like retrieving delivery medium info before really making the request. It is easier than approach  1 but it might not sound a good design as it makes sendchatmessage complex.

And there is another approach, which sounds the easiest, but not a completed solution though. Just add parameter delivery medium to sendchatmessage with default value BABEL, as the Hangups does. Then still let users manage conversations and pass in proper delivery medium value when they call sendchatmessage.

What do you think? Looking forward to hearing back from you. Thank you!

-----Original Message-----

**Comment by wingc-china** [comment]
Hi algesten,

Even I still have not decided to make the conversation component as the Hangups does, or just make the sendchatmessage(...) a little advanced, but a new parameter delivery_medium is needed to sendchatmessage(...) anyway. I updated the code to have that with default value BABEL so nothing will be broken.
I have updated the README.md to reflect all changes I made. Please take a look.

Thanks

**Comment by wingc-china** [comment]
Hi algesten, will you take a look if the changes are good to be merged? No matter what we will make next, the changes in this pull request should be good enough for now.

**Comment by algesten** [comment]
looks good to me. as it stands, this changes the signature of sendchatmessage. so it's a major upgrade. can you maintain the order of the sendchatmessage parameters and just add the new param last. that way it's not a breaking change.

**Comment by wingc-china** [comment]
Thanks! Just realized you replied. I will do that and update the PR.

**Pull request merged**
